# Site
name: "askPio"
description: "askPio, Bot, AI, LUIS"
meta_description: "askPio blog"
logo: 'assets/images/logo.png'
favicon: 'https://content.askpio.com/favicon/favicon.ico'
baseurl: ''
mainurl: 'http://askpio.com'
google_analytics: 'UA-132318762-1'
disqus: 'https-blog-subwai-com'
mailchimp-list: 'https://subwai.us20.list-manage.com/subscribe/post?u=e01c7eea6ace40984a93be00d&amp;id=98ff40b631'

# Authors
authors:
  sal:
    name: askPio Team
    display_name: askPio Team
    gravatar: 35be3d2ebffa6d9ee03e64328e6988eb
    email: info.askpio@gmail.com
    web: https://blog.askpio.com
    twitter: https://twitter.com/
    description: "Askpio Description"
  john:
    name: askPio Team  
    display_name: askPio Team
    gravatar: 35be3d2ebffa6d9ee03e64328e6988eb
    email: info.askpio@gmail.com
    web: https://blog.askpio.com
    twitter: https://twitter.com/Subwai1
    description: "This is the author box."
  rinkal:
    name: askPio Team  
    display_name: askPio Team
    gravatar: 35be3d2ebffa6d9ee03e64328e6988eb
    email: info.askpio@gmail.com
    web: https://blog.askpio.com
    twitter: https://twitter.com/Subwai1
    description: "R&D department of Askpio.com"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
